apiVersion: v1
kind: Service
metadata:
  name: forum-admin-service
spec:
  selector:
    app: forum-admin
  ports:
    - name: http-10007
      protocol: TCP
      port: 10007
      targetPort: 10007
  type: ClusterIP
