apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-admin-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forum-admin
  template:
    metadata:
      labels:
        app: forum-admin
    spec:
      containers:
        - name: forum-admin
          image: goutouz/forum-rpc-admin:latest
          env:
            - name: CONFIG_PATH
              value: "/config"
            - name: ACCESSKEYID
              valueFrom:
                secretKeyRef:
                  name: forum-secret
                  key: OSS_ACCESSKEYID
            - name: ACCESSKEYSECRET
              valueFrom:
                secretKeyRef:
                  name: forum-secret
                  key: OSS_ACCESSKEYSECRET
            - name: ROLEARN
              valueFrom:
                secretKeyRef:
                  name: forum-secret
                  key: OSS_ROLEARN
          envFrom:
            - secretRef:
                name: forum-secret
              
          volumeMounts:
            - name: forum-config
              mountPath: /config
              readOnly: true
          ports:
            - containerPort: 10007
      
      volumes:
        - name: forum-config
          configMap:
            name: forum-config
