apiVersion: v1
kind: Service
metadata:
  name: forum-user-service
spec:
  selector:
    app: forum-user
  ports:
    - name: http-10003
      protocol: TCP
      port: 10003
      targetPort: 10003
  type: ClusterIP
