apiVersion: v1
kind: Service
metadata:
  name: forum-static-service
spec:
  selector:
    app: forum-static
  ports:
    - name: http-10004
      protocol: TCP
      port: 10004
      targetPort: 10004
  type: ClusterIP
